-- =====================================================================
-- Task 1: Identity & Access - Users Table Schema
-- Reference: schema/tables.dbml
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(150) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    role                VARCHAR(50) NOT NULL,
    account_status      VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    is_email_verified   BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at       TIMESTAMP NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('STUDENT', 'PLACEMENT_OFFICER', 'ADMIN', 'RECRUITER')),
    CONSTRAINT chk_users_account_status CHECK (account_status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_account_status ON users (account_status);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);
CREATE INDEX IF NOT EXISTS idx_users_role_active ON users (role, is_active);

-- =====================================================================
-- Task 2: Student Profile & Related Tables Schema
-- Reference: schema/tables.dbml, schema/student_portal1.json & schema/admin_portal.txt
-- =====================================================================

CREATE TABLE IF NOT EXISTS student_profiles (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT NOT NULL,
    roll_no                     VARCHAR(20) NULL,

    -- Personal / Contact Details
    full_name                   VARCHAR(120) NOT NULL,
    email                       VARCHAR(150) NOT NULL,
    phone                       VARCHAR(20) NULL,
    address                     VARCHAR(255) NULL,
    about                       TEXT NULL,
    avatar_url                  TEXT NULL,
    resume_url                  TEXT NULL,

    -- Academic Details
    college                     VARCHAR(150) NULL,
    degree                      VARCHAR(100) NULL,
    department                  VARCHAR(100) NULL,
    department_code             VARCHAR(10) NULL,
    batch                       VARCHAR(20) NULL,
    semester                    SMALLINT NULL,
    cgpa                        DECIMAL(4,2) NULL,
    total_backlogs              INT NOT NULL DEFAULT 0,
    active_backlogs             INT NOT NULL DEFAULT 0,

    -- Placement Details
    placement_status            VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    is_open_to_opportunities    BOOLEAN NOT NULL DEFAULT TRUE,
    placed_company_id           BIGINT NULL,
    placed_ctc                  DECIMAL(12,2) NULL,
    placed_on                   DATE NULL,
    profile_completion_percent  SMALLINT NOT NULL DEFAULT 0,

    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT uq_student_profiles_user UNIQUE (user_id),
    CONSTRAINT uq_student_profiles_roll_no UNIQUE (roll_no),
    CONSTRAINT fk_student_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_student_semester CHECK (semester IS NULL OR (semester >= 1 AND semester <= 10)),
    CONSTRAINT chk_student_cgpa CHECK (cgpa IS NULL OR (cgpa >= 0.00 AND cgpa <= 10.00)),
    CONSTRAINT chk_student_profile_completion CHECK (profile_completion_percent >= 0 AND profile_completion_percent <= 100),
    CONSTRAINT chk_student_backlogs CHECK (active_backlogs <= total_backlogs),
    CONSTRAINT chk_student_placement_status CHECK (placement_status IN ('PENDING', 'ACTIVE', 'PLACED', 'BLOCKED')),
    CONSTRAINT chk_student_placed_company CHECK (placement_status <> 'PLACED' OR placed_company_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS student_skills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT NOT NULL,
    skill_name  VARCHAR(60) NOT NULL,
    proficiency VARCHAR(20) NULL,

    -- Constraints
    CONSTRAINT uq_student_skill UNIQUE (student_id, skill_name),
    CONSTRAINT fk_student_skills_student FOREIGN KEY (student_id) REFERENCES student_profiles(id) ON DELETE CASCADE,
    CONSTRAINT chk_student_skills_proficiency CHECK (proficiency IS NULL OR proficiency IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED'))
);

CREATE TABLE IF NOT EXISTS student_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT NOT NULL,
    document_name VARCHAR(150) NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    file_url      TEXT NOT NULL,
    file_size     BIGINT NULL,
    status        VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    verified_by   BIGINT NULL,
    verified_at   TIMESTAMP NULL,
    uploaded_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT fk_student_documents_student FOREIGN KEY (student_id) REFERENCES student_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_student_documents_verified_by FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_student_documents_type CHECK (document_type IN ('RESUME', 'MARKSHEET', 'CERTIFICATE', 'ID_PROOF', 'OTHER')),
    CONSTRAINT chk_student_documents_status CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT chk_student_documents_verification CHECK (status <> 'VERIFIED' OR verified_by IS NOT NULL)
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_profiles_user ON student_profiles (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_profiles_roll_no ON student_profiles (roll_no);
CREATE INDEX IF NOT EXISTS idx_student_department_code ON student_profiles (department_code);
CREATE INDEX IF NOT EXISTS idx_student_cgpa ON student_profiles (cgpa);
CREATE INDEX IF NOT EXISTS idx_student_placement_status ON student_profiles (placement_status);
CREATE INDEX IF NOT EXISTS idx_student_semester ON student_profiles (semester);
CREATE INDEX IF NOT EXISTS idx_student_placed_company ON student_profiles (placed_company_id);
CREATE INDEX IF NOT EXISTS idx_student_dept_cgpa ON student_profiles (department_code, cgpa);
CREATE INDEX IF NOT EXISTS idx_student_status_dept ON student_profiles (placement_status, department_code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_skill ON student_skills (student_id, skill_name);
CREATE INDEX IF NOT EXISTS idx_student_skills_student ON student_skills (student_id);
CREATE INDEX IF NOT EXISTS idx_student_skills_name ON student_skills (skill_name);

CREATE INDEX IF NOT EXISTS idx_student_documents_student ON student_documents (student_id);
CREATE INDEX IF NOT EXISTS idx_student_documents_status ON student_documents (status);
CREATE INDEX IF NOT EXISTS idx_student_documents_type ON student_documents (student_id, document_type);

